export const testInitialItems = [
	{
		id: "2",
		value: "put some pants on",
		parent: null,
		column: 0,
		userId: "1",
		children: null,
		depth: 0,
		index: 1,
		isLast: true,
		parentId: null,
	},
	{
		id: "4",
		value: "first put on a shirt ",
		parent: null,
		column: 0,
		userId: "1",
		children: null,
		depth: 1,
		index: 0,
		isLast: true,
		parentId: null,
	},
	{
		id: "1",
		value: "dress youself for gods sake!",
		parent: null,
		column: 0,
		userId: "1",
		children: null,
		depth: 0,
		index: 0,
		isLast: false,
		parentId: null,
	},
];

export const testSendItems = [
	{
		id: "2",
		value: "put some pants on",
		parent: null,
		column: 0,
		userId: "1",
		children: null,
		depth: 0,
		index: 1,
		isLast: true,
		parentId: null,
	},
	{
		id: "4",
		value: "first put on a shirt ",
		parent: null,
		column: 0,
		userId: "1",
		children: null,
		depth: 1,
		index: 0,
		isLast: true,
		parentId: null,
	},
	{
		id: "1",
		value: "dress youself for gods sake!",
		parent: null,
		column: 0,
		userId: "1",
		children: null,
		depth: 0,
		index: 0,
		isLast: false,
		parentId: null,
	},
];
